#!/bin/sh
# Simple set of scripts to create system state diagrams with rrdtool.
#
# @author Bernhard R. Fischer
# 

# look for default config file and pull in (if exists)
if test -e $HOME/.sysgr.conf ; then
   . $HOME/.sysgr.conf
fi 
# check for availability of rrdtool
if test -z "$RRDTOOL" ; then
   RRDTOOL=rrdtool
fi
which $RRDTOOL >/dev/null
if test $? -ne 0 ; then
   echo "rrdtool seems not to be missing. Please install rrdtool!"
   exit 1
fi
# path to monitoring scripts
if test -z "$RRDSCRIPTS" ; then
   fpath=$(dirname $(realpath $0))
   RRDSCRIPTS=$fpath/rrdscripts
fi
# destination directory (for PNGs, RRDs,...)
if test -z "$RRDHOME" ; then
   RRDHOME=./var
fi

# RRD image dimensions
W=800
H=400

# list of color values used. Add values here if you have more than 10 values
# within a single diagram.
COLORS="#00ff00 #0000ff #ffb000 #ff0000 #ff00ff #00ffff #8FBC8F #8B0000 #556B2F #9400D3"

HOSTNAME=$(hostname -f)

error_exit()
{
   echo $1
   rm $LOCK
   exit 1
}


init_html()
{
   echo "<!DOCTYPE html>" >$RRDHOME/$sbase.html
   if test $? -ne 0 ; then
      error_exit "cannot redirect to HTML file"
   fi
}


wr_html()
{
   echo $@ >>$RRDHOME/$sbase.html
   if test $? -ne 0 ; then
      error_exit "cannot redirect to HTML file"
   fi
}


rrd_graph()
{
   $RRDTOOL graph $RRDHOME/${sc}${1}.png -w $W -h $H \
      --start end-${1}d \
      --vertical-label "$RRDVLABEL" \
      $RRDOPTIONS \
      $def \
      $line \
      >/dev/null
   wr_html "<td><a data-fancybox='gallery' href='${sc}${1}.png'><img width='400' src='${sc}${1}.png' alt='$RRDVLABEL-${1}d'/></a></td>"
}


sbase=$(basename $0)

# path to lock file, to prevent script from run multiple times in parallel
LOCK=/tmp/$sbase.lock

# check command line parameters
if test -n "$1" ; then
   case $1 in
      help)
         cat << !
$0 [options]
   help ..... Output this help.
   unlock ... Remove lock file if locked.
!
         exit 0
         ;;

      unlock)
         rm -f $LOCK
         exit 0
         ;;
   esac
fi

umask 022

# exit if locked (if script is already executed)
# this is to prevent a system overload in case of something got stuck and the
# script is called by cron that it is not started over and over again.
if test -e $LOCK ; then
   echo "locked!"
   exit
fi
touch $LOCK

# create destination directory if not exists
if test ! -d $RRDHOME ; then
   mkdir -p $RRDHOME
   # safety check
   if test $? -ne 0 ; then
      error_exit "mkdir failed"
   fi
fi

# init HTML index file
init_html
wr_html "
   <html>
      <head>
         <title>$HOSTNAME system health</title>
         <script src='//code.jquery.com/jquery-3.3.1.min.js'></script>
         <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.css'/>
         <script src='https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.js'></script>
         <meta http-equiv='refresh' content='300'/>
         <meta name='author' content='sysgr by Bernhard R. Fischer'/>
         <meta charset='UTF-8'>
      </head>
      <body>
      $(date)
      <table>"

# loop over all scripts found in RRDSCRIPTS
for sc in $RRDSCRIPTS/*.sh
do

   RRDDATA=
   RRDVLABEL=
   # should be set to GAUGE oder COUNTER. GAUGE is default if empty
   RRDVTYPE=
   # additional options passed directly to rrdgraph
   RRDOPTIONS=

   . $sc

   sc=$(basename $sc)
   sc=${sc%%.sh}

   # set default value type to GAUGE (of omitted)
   if test -z "$RRDVTYPE" ; then
      RRDVTYPE=GAUGE
   fi

   # simple loop counter
   i=1
   # variable for rrd DEF string
   def=
   # variable for rrd LINE string
   line=

   # loop over all values within RRDDATA
   for ds in $RRDDATA
   do
      # split into name and value
      val=${ds##*:}
      name=${ds%%:*}
      # delete [/.] chars, squeeze [-], truncate to 19 bytes (required by rrdtool DS format)
      fname=$(echo $name | tr -d /. | tr -s - | head -c 19)
      rrd=$RRDHOME/$sc-$fname.rrd

      # create RRD if not exists
      if test ! -e $rrd ; then
         $RRDTOOL create $rrd -s 300 \
            DS:$fname:$RRDVTYPE:600:0:U \
            RRA:AVERAGE:0.5:1:210816 RRA:AVERAGE:0.5:12:8784 RRA:AVERAGE:0.5:288:366
      fi

      # update RRD
      $RRDTOOL update $rrd N:$val
      echo "$fname:$(date +%s):$val" >>$RRDHOME/$sbase.log

      # create definition options for rrdgraph
      defi="DEF:ds${i}=${rrd}:${fname}:AVERAGE"
      def="$def $defi"
      col=$(echo $COLORS | cut -d \  -f $i)
      linei="LINE1:ds${i}${col}:${name}"
      line="$line $linei"

      # increase counter
      i=$(($i + 1))
   done

   # set default label if it was omitted
   if test -z "$RRDVLABEL" ; then
      RRDVLABEL=$sc
   fi

   # create pngs for 1 7 and 28 days
   wr_html "<tr>"
   rrd_graph 1
   rrd_graph 7
   rrd_graph 28
   wr_html "</tr>"

done

# end HTML file
wr_html "</table></body></html>"

# remove lock file end exit
rm $LOCK
exit 0


